### ISSUE TITLE
multiple definition of `regressionMain(int, char* const*)'

### ISSUE THREAD

**Issue by lars-kuehne** [ogdf/ogdf#4]
On ogdf-snapshot-2014-02-28. I only changed the installPrefix in the makeMakefile.config, ran makeMakefile.sh and then make. It results in a multiple definition error:

g++ -o test/test-release _release/test/generators_test.o _release/test/gtest/gtest-all.o _release/test/main.o _release/test/regression-tests/main.o _release/test/regression-tests/reg-energy-based.o _release/test/regression-tests/reg-lca.o _release/test/regression-tests/reg-main.o _release/test/regression-tests/reg-planar-layout.o _release/test/regression-tests/reg-planarity-test.o _release/test/regression-tests/reg-planarization-layout.o _release/test/regression-tests/reg-sugiyama.o -pthread -L_release -lOGDF -lCOIN 
_release/test/regression-tests/reg-main.o: In function `regressionMain(int, char* const*)':
reg-main.cpp:(.text+0x20): multiple definition of `regressionMain(int, char* const*)'
_release/test/regression-tests/main.o:main.cpp:(.text+0x20): first defined here
collect2: error: ld returned 1 exit status
make: *** [test/test-release] Error 1

**Comment by sbeyer** [comment]
Thanks. The issue has been resolved by our transition from the old regression tests to bandit (this happened in 841d80f).
